all: main.exe program.exe

main.exe: maths.o main.c strings.o
	gcc main.c maths.o strings.o -o main.exe
	.\main.exe

maths.o: maths.h maths.c
	gcc -c maths.c -o maths.o

strings.o:strings.h strings.c
	gcc -c strings.c -o strings.o

program.exe: strings.o program.c
	gcc program.c strings.o -o program.exe
	.\program.exe


clean:
	del *.o *.exe